spring:
  profiles:
    include:
      - stock
      - redis
      - log
    active: online # 当前运行环境

  redis: # redis配置
    main:
      database: 1
      host: 47.104.29.59
      port: 6380
      password: lss19890228
      timeout: 2s
      lettuce:
        pool:
          max-active: 8
          min-idle: 0
          max-idle: 8
          max-wait: 1000ms
    stock:
      database: 2
      host: 47.104.29.59
      port: 6380
      password: lss19890228
      timeout: 2s
      lettuce:
        pool:
          max-active: 8
          min-idle: 0
          max-idle: 8
          max-wait: 1000ms
    user:
      database: 3
      host: 47.104.29.59
      port: 6380
      password: lss19890228
      timeout: 2s
      lettuce:
        pool:
          max-active: 8
          min-idle: 0
          max-idle: 8
          max-wait: 1000ms

  quartz:
    jdbc:
      initialize-schema: never
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: "clusteredScheduler"
            instanceId: "AUTO"
  mail:
    host: smtp.mxhichina.com
    username: lusongsong@1fox3.com
    password: "`lss19890228"
    protocol: smtp
    default-encoding: UTF-8

login:
  aes:
    key: cdb2b4b4bd6a4a710757ceaf5461d9bc

open:
  wechat-mini:
    url:
      login: http://open.1fox3.com/open/wechatMini/Login/index
