redis:
  class:
    time: #根据类名设置默认缓存时间
      UserLogin: 7200

  stock:
    stock:
      hash: stockRedisHash #股票在缓存中使用的队列
      list: stockRedisList #股票在缓存中使用的队列
      id-list: stockRedisIdList #股票id在缓存中使用的队列
      heat-list: stockRedisHeatList # 用户当前正在访问的股票列表,一般用于预加载实时分钟线图数据，因为网易接口只支持当个查询，使用线程网络负载有点大
    realtime:
      stock:
        rank:
          uptick-statistics: stockRealtimeStockUptickRateStatistics
          uptick: stockRealtimeStockUptickRateZSet
          surge: stockRealtimeStockSurgeRateZSet
          deal:
            num: stockRealtimeStockDealNumZSet
            money: stockRealtimeStockDealMoneyZSet
        info:
          hash: stockRealtimeStockInfoHash #股票在缓存中使用的hash表
        line:
          single: "stockRealtimeStockLineSingle:"
          hash: stockRealtimeStockLineHash
