server:
  port: 8081 #启动端口

spring:
  datasource: #数据库配置
    url: jdbc:mysql://39.99.226.98:3306/api?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Lyx20170212
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 不同的数据源配置
    stock:
      url: jdbc:mysql://39.99.226.98:3306/stock?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Lyx20170212
      driver-class-name: com.mysql.cj.jdbc.Driver
    user:
      url: jdbc:mysql://39.99.226.98:3306/user?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Lyx20170212
      driver-class-name: com.mysql.cj.jdbc.Driver
    api:
      url: jdbc:mysql://39.99.226.98:3306/api?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Lyx20170212
      driver-class-name: com.mysql.cj.jdbc.Driver
    quartz:
      url: jdbc:mysql://39.99.226.98:3306/quartz?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Lyx20170212
      driver-class-name: com.mysql.cj.jdbc.Driver
    admin:
      url: jdbc:mysql://39.99.226.98:3306/admin?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Lyx20170212
      driver-class-name: com.mysql.cj.jdbc.Driver

# 阿里接口账号信息
ali:
  api:
    account:
      app-key: 203769816
      app-secret: 5ecdmkzsqysdjvg58ktwmcwt8t5vjvq1
      app-code: ae29555a60b343fd9a9e80629b4f21e2

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  # 针对数据源的mapper路径
  stock:
    mapper-location: classpath:mybatis/mapper/stock/*.xml
  user:
    mapper-location: classpath:mybatis/mapper/user/*.xml
  api:
    mapper-location: classpath:mybatis/mapper/api/*.xml
  quartz:
    mapper-location: classpath:mybatis/mapper/quartz/*.xml
  admin:
    mapper-location: classpath:mybatis/mapper/admin/*.xml



