stock:
  market:
    sh:
      stock-market-name: 沪
      stock-market: 1
    sz:
      stock-market-name: 深
      stock-market: 2
    hk:
      stock-market-name: 港
      stock-market: 3
  type:
    index:
      stock-type-name: 指数
      stock-type: 1
    stock:
      stock-type-name: 股票
      stock-type: 2
    fund:
      stock-type-name: 基金
      stock-type: 3
    bond:
      stock-type-name: 债券
      stock-type: 4
    warrant:
      stock-type-name: 权证
      stock-type: 5
  kind:
    sh-index:
      stock-kind-name: 沪指
      stock-market: 1
      stock-type: 1
      stock-kind: 1
      per-code:
        - "000"
    sh-stock-a:
      stock-kind-name: 沪A
      stock-market: 1
      stock-type: 2
      stock-kind: 2
      per-code:
        - "600"
        - "601"
        - "603"
    sh-stock-b:
      stock-kind-name: 沪B
      stock-market: 1
      stock-type: 2
      stock-kind: 3
      per-code:
        - "900"
    sh-stock-star:
      stock-kind-name: 科创
      stock-market: 1
      stock-type: 2
      stock-kind: 4
      per-code:
        - "688"
    sh-fund:
      stock-kind-name: 沪基
      stock-market: 1
      stock-type: 3
      stock-kind: 5
      per-code:
        - "500"
        - "501"
        - "502"
        - "505"
        - "510"
        - "511"
        - "512"
        - "513"
        - "515"
        - "518"
        - "519"
        - "522"
        - "523"
    sh-bond:
      stock-kind-name: 沪债
      stock-market: 1
      stock-type: 4
      stock-kind: 6
      per-code:
        - "010"
        - "018"
        - "019"
        - "020"
        - "090"
        - "091"
        - "100"
        - "102"
        - "103"
        - "104"
        - "105"
        - "106"
        - "108"
        - "110"
        - "113"
        - "120"
        - "122"
        - "124"
        - "127"
        - "130"
        - "132"
        - "133"
        - "134"
        - "136"
        - "140"
        - "141"
        - "143"
        - "144"
        - "147"
        - "152"
        - "155"
        - "157"
        - "160"
        - "163"
        - "182"
        - "190"
        - "191"
        - "192"
        - "201"
        - "202"
        - "204"
        - "751"
    sz-index:
      stock-kind-name: 深指
      stock-market: 2
      stock-type: 1
      stock-kind: 7
      per-code:
        - "399"
    sz-stock-a:
      stock-kind-name: 深A
      stock-market: 2
      stock-type: 2
      stock-kind: 8
      per-code:
        - "000"
        - "001"
        - "002"
        - "003"
    sz-stock-b:
      stock-kind-name: 深B
      stock-market: 2
      stock-type: 2
      stock-kind: 9
      per-code:
        - "200"
        - "201"
    sz-stock-gem:
      stock-kind-name: 创业
      stock-market: 2
      stock-type: 2
      stock-kind: 10
      per-code:
        - "300"
    sz-fund:
      stock-kind-name: 深基
      stock-market: 2
      stock-type: 3
      stock-kind: 11
      per-code:
        - "150"
        - "159"
        - "16"
        - "184"
    sz-bond:
      stock-kind-name: 深债
      stock-market: 2
      stock-type: 4
      stock-kind: 12
      per-code:
        - "10"
        - "111"
        - "112"
        - "120"
        - "123"
        - "127"
        - "128"
        - "131"
        - "149"
    hk-stock:
      stock-kind-name: 港股
      stock-market: 3
      stock-type: 2
      stock-kind: 13
      per-code:
        - "00"
        - "01"
        - "020"
        - "021"
        - "022"
        - "023"
        - "024"
        - "025"
        - "026"
        - "027"
        - "0285"
        - "0286"
        - "0287"
        - "0288"
        - "0289"
        - "029"
        - "033"
        - "036"
        - "037"
        - "038"
        - "039"
        - "043"
        - "046"
        - "060"
        - "061"
        - "062"
        - "068"
        - "069"
        - "080"
        - "081"
        - "082"
        - "083"
        - "084"
        - "085"
        - "086"
        - "099"
    hk-fund:
      stock-kind-name: 港基
      stock-market: 3
      stock-type: 3
      stock-kind: 14
      per-code:
        - "0280"
        - "0281"
        - "0282"
        - "0283"
        - "0284"
        - "030"
        - "031"
        - "072"
        - "073"
        - "075"
        - "090"
        - "091"
        - "098"
        - "807"
        - "828"
        - "830"
        - "831"
        - "870"
    hk-warrant:
      stock-kind-name: 权证
      stock-market: 3
      stock-type: 5
      stock-kind: 15
      per-code:
        - "100"
        - "101"
        - "11"
        - "121"
        - "122"
        - "123"
        - "124"
        - "125"
        - "126"
        - "127"
        - "128"
        - "129"
        - "13"
        - "14"
        - "15"
        - "16"
        - "17"
        - "18"
        - "19"
        - "2"
        - "47"
        - "480"
        - "481"
        - "5"
        - "6"
  top-index:
    - {stock-market: 1, stock-code: "000001"} #上证指数
    - {stock-market: 2, stock-code: "399001"} #深证成指
    - {stock-market: 2, stock-code: "399006"} #创业板指
    - {stock-market: 3, stock-code: "HSI"} #恒生指数
    - {stock-market: 3, stock-code: "HSCEI"} #国企指数
  demo-index:
    - {stock-market: 1, stock-code: "000001"} #上证指数
    - {stock-market: 2, stock-code: "399001"} #深证成指
    - {stock-market: 3, stock-code: "HSI"} #恒生指数
