redis:
  class:
    time: #根据类名设置默认缓存时间
      UserLogin: 7200

  stock:
    stock:
      list: stockRedisList #股票在缓存中使用的队列
      code-list: stockRedisCodeList #股票编码在缓存中使用的队列
    realtime:
      stock:
        rank:
          up-limit:
            list: stockRealtimeUpLimitList
          down-limit:
            list: stockRealtimeDownLimitList
          stop: stockRealtimeStockStopStatistics
          uptick-statistics: stockRealtimeStockUptickRateStatistics
          price: stockRealtimeStockPriceZSet
          uptick: stockRealtimeStockUptickRateZSet
          surge: stockRealtimeStockSurgeRateZSet
          deal:
            num: stockRealtimeStockDealNumZSet
            money: stockRealtimeStockDealMoneyZSet
        info:
          hash: stockRealtimeStockInfoHash #股票在缓存中使用的hash表
        line:
          single: "stockRealtimeStockLineSingle:"
          hash: stockRealtimeStockLineHash
